version: 0.2

env:
  secrets-manager:
    SECRET_USERNAME:"pipeline-docker-auth:username"
    SECRET_PASSWORD:"pipeline-docker-auth:password"

phases:
  build:
    commands:
      - echo "Hello World from buildspec.yml"
      - echo "$SECRET_USERNAME"
  
artifacts:
  files:
    - Dockerfile